/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  created_at: Generated<string>;
  id: Generated<number>;
  owner_id: string;
}

export interface Permission {
  account_id: number;
  created_at: Generated<string>;
  id: Generated<number>;
  permission: string;
  user_id: string;
}

export interface User {
  created_at: Generated<string>;
  email: string | null;
  id: string;
  parent_id: number | null;
  registration_record: string | null;
  user_name: string;
}

export interface DB {
  account: Account;
  permission: Permission;
  user: User;
}
